IBKR_SUBSIDIARIES = {
    "australia": "Australia",
    "canada": "Canada",
    "hongkong": "Hong Kong",
    "india": "India",
    "japan": "Japan",
    "singapore": "Singapore",
    "uk": "United Kingdom",
    "usa": "United States",
}

IBKR_STOCKLOAN_COUNTRIES = {
    "australia": "Australia",
    "austria": "Austria",
    "belgium": "Belgium",
    "british": "United Kingdom",
    "canada": "Canada",
    "dutch": "Netherlands",
    "france": "France",
    "germany": "Germany",
    "hongkong": "Hong Kong",
    "india": "India",
    "italy": "Italy",
    "japan": "Japan",
    "mexico": "Mexico",
    "spain": "Spain",
    "swedish": "Sweden",
    "swiss": "Switzerland",
    "usa": "United States",
}
