
ECB_CURRENCIES = {
    "AUD": "Australian Dollar",
    "BGN": "Bulgarian Lev",
    "BRL": "Brazilian Real",
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "CNH": "Chinese Yuan",
    "CNY": "Chinese Yuan",
    "CYP": "Cypriot Pounds",
    "CZK": "Czech Koruna",
    "DKK": "Danish Krone",
    "EEK": "Estonian Kroon",
    "EUR": "Euro",
    "GBP": "British Pound",
    "GBX": "British Pence",
    "HKD": "Hong Kong Dollar",
    "HRK": "Croatian Kuna",
    "HUF": "Hungarian Forint",
    "IDR": "Indonesian Rupiah",
    "ILS": "Israeli Shekel",
    "INR": "Indian Rupee",
    "ISK": "Iceland Krona",
    "JPY": "Japanese Yen",
    "KRW": "South Korean Won",
    "LTL": "Lithuanian Litas",
    "LVL": "Latvian Lats",
    "MTL": "Maltese Lira",
    "MXN": "Mexican Peso",
    "MYR": "Malaysian Ringgit",
    "NOK": "Norwegian Krone",
    "NZD": "New Zealand Dollar",
    "PHP": "Philippine Peso",
    "PLN": "Polish Zloty",
    "ROL": "Romanian Leu",
    "RON": "Romanian Leu",
    "RUB": "Russian Ruble",
    "SEK": "Swedish Krona",
    "SGD": "Singapore Dollar",
    "SIT": "Albanian Tolar",
    "SKK": "Slovak Koruna",
    "THB": "Thai Baht",
    "TRL": "Turkish Lira",
    "TRY": "Turkish Lira",
    "USD": "US Dollar",
    "ZAR": "South African Rand",
}